version: '3.8'

services:
  web:
    build: .
    ports:
        - "8000:8000"

    depends_on:
      - db
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgres://joe:secret@db:5432/dice_roll
    volumes:
      - .:/app

  db:
    image: postgres:15

    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: joe
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dice_roll
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgdata:
  pgadmin-data: